export const designSystem = {
  typography: "Parent UI uses 16px minimum body text; child-facing labels pair short text with large visual cues.",
  spacing: "8px grid with 24px screen gutters and 48px minimum touch rows.",
  color: "Warm paper base, green trust actions, blue learning surfaces, amber progress, low-stimulus night mode.",
  icons: "Icons are symbolic support only; primary meaning remains in text or illustrated controls.",
  motion: "Short purposeful transitions under 260ms; bedtime mode removes bounce and loops.",
  breakpoints: ["320", "360", "390", "412", "768", "1024", "1440"],
  touchTarget: "All interactive controls are at least 44px high; primary child controls are at least 64px."
};

export const flows = [
  { id: "A", name: "First setup", pages: ["FL-HTML-01", "FL-HTML-02", "FL-HTML-03", "FL-HTML-04"] },
  { id: "B", name: "Story recommendation", pages: ["FL-HTML-04", "FL-HTML-05", "FL-HTML-06", "FL-HTML-07"] },
  { id: "C", name: "After-story learning", pages: ["FL-HTML-07", "FL-HTML-08", "FL-HTML-09", "FL-HTML-10"] },
  { id: "D", name: "Parent review", pages: ["FL-HTML-09", "FL-HTML-10", "FL-HTML-11"] },
  { id: "E", name: "Bedtime", pages: ["FL-HTML-11", "FL-HTML-12"] }
];

const commonStates = {
  default: "Primary content is available and the main CTA is enabled.",
  loading: "Show skeleton blocks, disable destructive actions, keep navigation visible.",
  empty: "Explain why content is missing and provide one recovery action.",
  error: "Use calm copy, preserve entered data, and offer retry.",
  success: "Confirm completion and offer the next safest step.",
  offline: "Keep cached story or task visible and queue changes until connection returns.",
  apiDelay: "Show calm waiting feedback, keep the prior safe content visible, and prevent repeated taps.",
  apiFailure: "Explain the service problem in parent-readable language and offer retry or cached fallback.",
  disabled: "Explain the disabled reason near the control.",
  permissionDenied: "Send parent to consent or settings; never ask the child to solve it."
};

export const pages = [
  {
    id: "FL-HTML-01",
    title: "First Launch",
    route: "#/first-launch",
    renderer: "firstLaunch",
    audience: "Parent",
    ageBand: "Adult caregiver",
    businessGoal: "Convert first open into trusted child setup.",
    userGoal: "Understand the product and begin setup within one tap.",
    pain: "The parent needs proof this is child-safe before giving any data.",
    sitemap: "Entry / onboarding",
    navigation: "No bottom navigation; setup and login exits only.",
    journey: "Download -> first open -> trust check -> setup",
    userFlow: "Open app, read one promise, inspect safety proof, start setup.",
    taskFlow: "Review value, confirm parent-managed model, tap Set up my child.",
    layoutFamily: "Immersive welcome with trust strip",
    components: ["brand mark", "story world preview", "trust strip", "primary CTA", "login link"],
    primaryCTA: "Set up my child",
    secondaryCTA: "I already have an account",
    copy: "Stories, growth, and bedtime for ages 0-6. Parent managed. No child account.",
    illustration: "Bright parent-and-child reading scene with gentle blocks and moon lamp.",
    interaction: "CTA advances to parent login; login link opens returning parent flow.",
    animation: "Hero art fades in once; reduced motion uses no transform.",
    accessibility: "Single H1, CTA first after explanation, contrast above AA, touch target 56px.",
    childSafety: "No direct child data entry; adult consent before child profile.",
    responsive: "320-412px single column; tablet centers the phone-width journey card.",
    api: "not applicable: no network before consent",
    states: commonStates,
    acceptance: ["Parent sees value within 3 seconds.", "No child account is requested.", "Only two forward choices are visible."],
    testIds: ["T-FIRST-001", "T-A11Y-001", "T-SAFE-001"]
  },
  {
    id: "FL-HTML-02",
    title: "Parent Login",
    route: "#/login",
    renderer: "login",
    audience: "Parent",
    ageBand: "Adult caregiver",
    businessGoal: "Create a consented parent session.",
    userGoal: "Log in without exposing adult credentials to the child.",
    pain: "Parents need a fast but secure gate before managing child data.",
    sitemap: "Entry / authentication",
    navigation: "Back to first launch; continue to child profile.",
    journey: "First open -> login -> child setup",
    userFlow: "Choose email or passkey, read privacy note, submit credentials.",
    taskFlow: "Enter email, enter password, log in, recover from validation errors.",
    layoutFamily: "Secure form with consent panel",
    components: ["email field", "password field", "privacy summary", "login CTA", "help link"],
    primaryCTA: "Log in",
    secondaryCTA: "Create parent account",
    copy: "Parent account required for consent, privacy choices, and progress review.",
    illustration: "Small lock and family notebook beside the form.",
    interaction: "Inline validation; submit locks button and shows loading state.",
    animation: "Field errors slide down 120ms; reduced motion shows instant message.",
    accessibility: "Labels are explicit; errors use aria-live; tab order follows form order.",
    childSafety: "Adult-only authentication; no child-facing encouragement to enter data.",
    responsive: "Form fields remain full width; help content moves under form on narrow screens.",
    api: "POST /auth/session",
    states: commonStates,
    acceptance: ["Invalid email shows inline error.", "Password is never shown by default.", "Privacy note links to parent policy."],
    testIds: ["T-AUTH-001", "T-ERROR-001", "T-A11Y-002"]
  },
  {
    id: "FL-HTML-03",
    title: "Create Child",
    route: "#/child",
    renderer: "childProfile",
    audience: "Parent",
    ageBand: "Adult caregiver",
    businessGoal: "Collect minimal child profile data for safe personalization.",
    userGoal: "Create a child profile with only necessary information.",
    pain: "Parents dislike apps asking for excessive child data.",
    sitemap: "Onboarding / child profile",
    navigation: "Back to login; continue to age band.",
    journey: "Login -> create child -> age input",
    userFlow: "Enter display name, choose avatar, confirm data minimization.",
    taskFlow: "Type nickname, select visual avatar, save profile.",
    layoutFamily: "Profile builder with data minimization checklist",
    components: ["nickname field", "avatar picker", "data checklist", "save CTA"],
    primaryCTA: "Continue to age",
    secondaryCTA: "Skip avatar",
    copy: "Use a nickname. We do not need a full name, photo, or birthday.",
    illustration: "Friendly guide character with selectable color badges.",
    interaction: "Avatar selection updates preview and save state.",
    animation: "Selected avatar gently scales once; reduced motion uses outline only.",
    accessibility: "Avatar choices have text labels; nickname field has helper text.",
    childSafety: "No full name, photo, location, school, or contact request.",
    responsive: "Avatar grid becomes two columns at 320px.",
    api: "POST /children",
    states: commonStates,
    acceptance: ["Full legal name is not requested.", "Save stays disabled until nickname exists.", "Avatar has accessible name."],
    testIds: ["T-CHILD-001", "T-PRIVACY-001", "T-STATE-001"]
  },
  {
    id: "FL-HTML-04",
    title: "Age Band",
    route: "#/age",
    renderer: "ageBand",
    audience: "Parent",
    ageBand: "0-2, 3-4, 5-6 child bands",
    businessGoal: "Set the cognitive baseline for recommendations.",
    userGoal: "Choose the child's age band and understand why it matters.",
    pain: "Parents need confidence that content matches development stage.",
    sitemap: "Onboarding / age band",
    navigation: "Back to child profile; continue to recommendation.",
    journey: "Create child -> choose age -> recommendation",
    userFlow: "Compare age bands, read ability notes, select one band.",
    taskFlow: "Select 0-2, 3-4, or 5-6, review guidance, confirm.",
    layoutFamily: "Age-specific comparison panels",
    components: ["age cards", "ability notes", "parent tip", "confirm CTA"],
    primaryCTA: "Use this age band",
    secondaryCTA: "Ask me later",
    copy: "Age changes story length, visual cues, questions, and bedtime pacing.",
    illustration: "Three developmental cards: look, name, tell.",
    interaction: "Selecting a band updates recommendation explanation.",
    animation: "Panel content crossfades; reduced motion swaps instantly.",
    accessibility: "Cards are radio buttons; selected state has text and border.",
    childSafety: "Age bands prevent reading-heavy UI for non-readers.",
    responsive: "Cards stack vertically on phones and form columns on tablet.",
    api: "PATCH /children/:id/age-band",
    states: commonStates,
    acceptance: ["2-year-old path states visual-first guidance.", "Selection is screen-reader announced.", "No precise birthdate required."],
    testIds: ["T-AGE-001", "T-COG-001", "T-A11Y-003"]
  },
  {
    id: "FL-HTML-05",
    title: "AI Story Recommendation",
    route: "#/recommendation",
    renderer: "recommendation",
    audience: "Parent",
    ageBand: "Selected child age band",
    businessGoal: "Start the first story with explainable personalization.",
    userGoal: "Pick a recommended story and know why it fits.",
    pain: "Parents do not trust black-box AI recommendations for children.",
    sitemap: "Home / today's story",
    navigation: "Bottom nav appears; play or browse alternatives.",
    journey: "Age band -> recommendation -> story player",
    userFlow: "Review recommended story, inspect fit reasons, start play.",
    taskFlow: "Read story card, verify age fit, tap Play story.",
    layoutFamily: "Explainable recommendation card plus alternatives",
    components: ["story hero", "fit reasons", "skill chips", "alternative list", "play CTA"],
    primaryCTA: "Play story",
    secondaryCTA: "See other stories",
    copy: "Recommended because Mia chose age 3-4, calm animals, and bedtime-friendly pacing.",
    illustration: "Forest story cover with soft animal characters.",
    interaction: "Alternative cards preview fit reasons before selecting.",
    animation: "Story card expands into player route; reduced motion uses fade.",
    accessibility: "Recommendation reasons are text, not only color chips.",
    childSafety: "No scary imagery, conflict, ads, or manipulative countdowns.",
    responsive: "Recommendation remains first; alternatives scroll horizontally on H5.",
    api: "GET /recommendations?childId=:id",
    states: commonStates,
    acceptance: ["Recommendation explains age fit.", "Parent can reject recommendation.", "Story start is one primary CTA."],
    testIds: ["T-REC-001", "T-PM-001", "T-SAFE-002"]
  },
  {
    id: "FL-HTML-06",
    title: "Child Story Player",
    route: "#/player",
    renderer: "player",
    audience: "Child with parent nearby",
    ageBand: "0-6, adapted by selected band",
    businessGoal: "Deliver the core story experience safely.",
    userGoal: "Listen, look, pause, and follow the story without reading.",
    pain: "Young children cannot use text-heavy playback controls.",
    sitemap: "Story / playback",
    navigation: "Back requires parent confirmation; finish leads to reflection.",
    journey: "Recommendation -> playback -> story end",
    userFlow: "Listen to page, use large controls, reach story end.",
    taskFlow: "Tap play or pause, swipe page, adjust volume with parent gate.",
    layoutFamily: "Immersive child player with oversized controls",
    components: ["story art", "progress dots", "large play button", "sound toggle", "parent gate"],
    primaryCTA: "Play or pause",
    secondaryCTA: "Parent controls",
    copy: "Look at the sleepy fox. Tap the big button to hear the next line.",
    illustration: "Full-screen calm illustrated scene with one focal character.",
    interaction: "Large central control toggles playback; swipe moves one story beat.",
    animation: "Scene pans slowly; reduced motion uses still image.",
    accessibility: "Audio captions available to parent; controls have labels.",
    childSafety: "No external links, purchases, ads, chat, or adult settings in child UI.",
    responsive: "Controls stay inside thumb zone and above device safe area.",
    api: "GET /stories/:id/pages and POST /progress/events",
    states: commonStates,
    acceptance: ["Primary control is at least 72px.", "Parent controls are gated.", "Offline cached story can continue."],
    testIds: ["T-PLAYER-001", "T-OFFLINE-001", "T-CHILD-UI-001"]
  },
  {
    id: "FL-HTML-07",
    title: "Story Complete",
    route: "#/complete",
    renderer: "complete",
    audience: "Child and parent",
    ageBand: "0-6, visual-first",
    businessGoal: "Convert completion into learning reflection.",
    userGoal: "Celebrate gently and answer one simple prompt.",
    pain: "Overstimulating rewards can disrupt bedtime and attention.",
    sitemap: "Story / completion",
    navigation: "Ask together, next story, or bedtime path.",
    journey: "Playback -> story complete -> reflection",
    userFlow: "See completion, answer one question, choose next step.",
    taskFlow: "Review visual recap, tap one feeling answer, continue.",
    layoutFamily: "Calm completion with one reflection prompt",
    components: ["completion scene", "single prompt", "visual answer buttons", "next CTA"],
    primaryCTA: "Ask together",
    secondaryCTA: "Choose next story",
    copy: "The fox found the quiet light. How did the fox feel?",
    illustration: "Soft recap card showing the ending moment.",
    interaction: "Answer buttons give gentle audio and visual confirmation.",
    animation: "Small sparkle fade only; bedtime removes celebration motion.",
    accessibility: "Prompt can be read aloud; visual answers include labels.",
    childSafety: "No streak pressure, no variable reward loop, no social comparison.",
    responsive: "Answer buttons form a two-by-two visual grid on phones.",
    api: "POST /progress/reflection",
    states: commonStates,
    acceptance: ["Only one prompt is shown.", "Reward is calm.", "Parent can skip reflection."],
    testIds: ["T-COMPLETE-001", "T-REWARD-001", "T-BEDTIME-SAFE-001"]
  },
  {
    id: "FL-HTML-08",
    title: "Next Recommendation",
    route: "#/next",
    renderer: "nextChoice",
    audience: "Parent",
    ageBand: "Adult caregiver",
    businessGoal: "Guide the next session without endless scrolling.",
    userGoal: "Choose continue, save, or stop confidently.",
    pain: "Parents need boundaries after a child finishes content.",
    sitemap: "Story / next step",
    navigation: "Home, saved list, bedtime, or daily task.",
    journey: "Story complete -> next recommendation -> task or bedtime",
    userFlow: "Review next option, inspect time estimate, decide.",
    taskFlow: "Choose next story, save for later, or start bedtime mode.",
    layoutFamily: "Decision board with time and stimulation labels",
    components: ["next story card", "time badge", "calmness meter", "save action", "stop action"],
    primaryCTA: "Save for later",
    secondaryCTA: "Start now",
    copy: "Next best: The Little Rain Drum. 4 minutes. Calm pace.",
    illustration: "Mini cover paired with time and energy indicators.",
    interaction: "Selecting stop recommends bedtime or parent task.",
    animation: "Cards slide less than 16px; reduced motion disables movement.",
    accessibility: "Time and calmness are text; not color-only.",
    childSafety: "No infinite autoplay; next story requires parent decision.",
    responsive: "Decision cards stack; destructive stop is visually separated.",
    api: "GET /recommendations/next",
    states: commonStates,
    acceptance: ["No autoplay chain.", "Time estimate is visible.", "Stop option is equal clarity."],
    testIds: ["T-NEXT-001", "T-DARKPATTERN-001", "T-UX-001"]
  },
  {
    id: "FL-HTML-09",
    title: "Daily Parent Task",
    route: "#/daily-task",
    renderer: "dailyTask",
    audience: "Parent",
    ageBand: "Adult caregiver leading child",
    businessGoal: "Extend story into one realistic parent-child activity.",
    userGoal: "Complete a short daily task with the child.",
    pain: "Parents need easy follow-up activities, not homework.",
    sitemap: "Daily tasks",
    navigation: "Task tab with back to home and completion route.",
    journey: "Next recommendation -> daily task -> parent interaction",
    userFlow: "Read task, gather object, start with child, mark progress.",
    taskFlow: "Choose 3-minute task, follow steps, mark done or skip.",
    layoutFamily: "Checklist activity with object cue",
    components: ["task card", "object cue", "three steps", "timer", "mark done CTA"],
    primaryCTA: "Start with child",
    secondaryCTA: "Skip today",
    copy: "Find something soft. Ask: What sound would it make in the rain story?",
    illustration: "Soft object and rain drum activity visual.",
    interaction: "Timer starts only after parent taps start; skip asks for reason.",
    animation: "Timer ring progresses smoothly; reduced motion uses numeric timer.",
    accessibility: "Steps are ordered text; timer does not rely on animation.",
    childSafety: "Activity uses safe household object and adult supervision.",
    responsive: "Checklist remains readable with 48px rows at 320px.",
    api: "GET /daily-tasks and POST /tasks/:id/start",
    states: commonStates,
    acceptance: ["Task takes under 5 minutes.", "Adult supervision is explicit.", "Skip path exists."],
    testIds: ["T-TASK-001", "T-SUPERVISION-001", "T-STATE-002"]
  },
  {
    id: "FL-HTML-10",
    title: "Parent Child Interaction",
    route: "#/interaction",
    renderer: "interaction",
    audience: "Parent and child together",
    ageBand: "3-6 with parent adaptation",
    businessGoal: "Increase parent-child engagement quality.",
    userGoal: "Guide a simple conversation without scripting the child.",
    pain: "Parents want prompts that feel natural, not robotic.",
    sitemap: "Daily tasks / interaction",
    navigation: "From daily task; exit to progress dashboard.",
    journey: "Daily task -> interaction -> progress",
    userFlow: "Read parent prompt, child responds visually or verbally, parent marks outcome.",
    taskFlow: "Ask, observe, choose response type, save note.",
    layoutFamily: "Split-role interaction board",
    components: ["parent prompt", "child visual choices", "observation note", "mark done CTA"],
    primaryCTA: "Mark done",
    secondaryCTA: "Save note only",
    copy: "Parent asks: Which sound was soft? Child can point, say, or tap.",
    illustration: "Two-panel parent-child prompt with pointing choices.",
    interaction: "Parent notes response; child choices are large and optional.",
    animation: "Choice confirmation pulses once; reduced motion uses check mark.",
    accessibility: "Parent instructions and child choices are separated semantically.",
    childSafety: "Does not grade the child; accepts pointing, sound, or silence.",
    responsive: "Parent panel appears before child choices on small screens.",
    api: "POST /interactions",
    states: commonStates,
    acceptance: ["No wrong-answer language.", "Multiple response modes are accepted.", "Parent note can be saved privately."],
    testIds: ["T-INTERACT-001", "T-INCLUSION-001", "T-NOTE-001"]
  },
  {
    id: "FL-HTML-11",
    title: "Parent Dashboard",
    route: "#/dashboard",
    renderer: "dashboard",
    audience: "Parent",
    ageBand: "Adult caregiver",
    businessGoal: "Show growth signals and next best parent action.",
    userGoal: "Review progress without over-measuring the child.",
    pain: "Parents need insight but not pressure or comparison.",
    sitemap: "Parent center / progress",
    navigation: "Parent tab; links to privacy, export, settings, bedtime.",
    journey: "Interaction -> progress review -> bedtime",
    userFlow: "Review week, read pattern, choose next action.",
    taskFlow: "Open dashboard, inspect signal cards, start bedtime or privacy action.",
    layoutFamily: "Parent analytics with humane progress language",
    components: ["weekly summary", "skill signals", "privacy shortcuts", "bedtime CTA"],
    primaryCTA: "Review progress",
    secondaryCTA: "Start bedtime",
    copy: "Mia listened calmly 4 times and answered with pointing twice this week.",
    illustration: "Gentle progress cards, no leaderboard.",
    interaction: "Cards expand for evidence; privacy actions require parent session.",
    animation: "Charts fill once; reduced motion shows completed bars.",
    accessibility: "Charts include text summaries and table fallback.",
    childSafety: "No comparison, ranking, public sharing, or pressure metrics.",
    responsive: "Cards become one-column and retain data labels.",
    api: "GET /progress/summary",
    states: commonStates,
    acceptance: ["Progress is descriptive, not competitive.", "Privacy shortcut is visible.", "Chart has text equivalent."],
    testIds: ["T-DASH-001", "T-PRIVACY-002", "T-A11Y-004"]
  },
  {
    id: "FL-HTML-12",
    title: "Bedtime Mode",
    route: "#/bedtime",
    renderer: "bedtime",
    audience: "Parent and child",
    ageBand: "0-6 bedtime context",
    businessGoal: "Support repeat usage in a calm nightly routine.",
    userGoal: "Start a low-stimulation story and end cleanly.",
    pain: "Parents need the app to help bedtime, not extend screen time.",
    sitemap: "Bedtime",
    navigation: "From dashboard or next recommendation; exits to lock screen.",
    journey: "Progress review -> bedtime -> end session",
    userFlow: "Dim interface, choose calm story, play, end with no autoplay.",
    taskFlow: "Set duration, start bedtime story, finish and lock next actions.",
    layoutFamily: "Low-stimulation night routine",
    components: ["dim theme", "duration picker", "calm story card", "night controls", "end session CTA"],
    primaryCTA: "Start bedtime story",
    secondaryCTA: "End tonight",
    copy: "One calm story. No autoplay. Screen dims after the final page.",
    illustration: "Moonlit room, soft blanket, single calm focal image.",
    interaction: "Duration picker changes story length; end disables next-story prompts.",
    animation: "No bounce; only slow opacity. Reduced motion uses static dimming.",
    accessibility: "High contrast in dark mode; audio can continue with screen dimmed.",
    childSafety: "No autoplay, no streak, no bright reward, no endless scroll.",
    responsive: "Controls stay low in thumb zone; dark mode respects safe areas.",
    api: "POST /bedtime/session",
    states: commonStates,
    acceptance: ["No next-story autoplay.", "End state is obvious.", "Brightness and motion are reduced."],
    testIds: ["T-BEDTIME-001", "T-MOTION-001", "T-AUTOPLAY-001"]
  }
];
