export const designSystem = {
  typography: "Parent UI uses 16px minimum body text; child-facing labels pair short text with large visual cues.",
  spacing: "8px grid with 24px screen gutters and 48px minimum touch rows.",
  color: "Warm paper base, green trust actions, blue learning surfaces, amber progress, low-stimulus night mode.",
  icons: "Icons are symbolic support only; primary meaning remains in text or illustrated controls.",
  motion: "Short purposeful transitions under 260ms; bedtime mode removes bounce and loops.",
  breakpoints: ["320", "360", "390", "412", "768", "1024", "1440"],
  touchTarget: "All interactive controls are at least 44px high; primary child controls are at least 64px."
};

export const flows = [
  { id: "A", name: "First setup", pages: ["FL-HTML-13", "FL-HTML-14", "FL-HTML-16", "FL-HTML-02", "FL-HTML-03", "FL-HTML-04", "FL-HTML-17", "FL-HTML-18"] },
  { id: "B", name: "Story recommendation", pages: ["FL-HTML-18", "FL-HTML-05", "FL-HTML-22", "FL-HTML-06", "FL-HTML-07", "FL-HTML-08", "FL-HTML-18"] },
  { id: "C", name: "Explore and save", pages: ["FL-HTML-18", "FL-HTML-21", "FL-HTML-20", "FL-HTML-22", "FL-HTML-06", "FL-HTML-24", "FL-HTML-25"] },
  { id: "D", name: "Parent controls", pages: ["FL-HTML-18", "FL-HTML-26", "FL-HTML-27", "FL-HTML-11", "FL-HTML-28", "FL-HTML-31", "FL-HTML-18"] },
  { id: "E", name: "Error recovery", pages: ["FL-HTML-06", "FL-HTML-33", "FL-HTML-34", "FL-HTML-35", "FL-HTML-18"] }
];

const commonStates = {
  default: "The page-specific story, parent, or recovery task is visible and the main CTA is enabled.",
  loading: "Show skeleton blocks, disable destructive actions, keep navigation visible.",
  empty: "Explain why content is missing and provide one recovery action.",
  error: "Use calm copy, preserve entered data, and offer retry.",
  success: "Confirm completion and offer the next safest step.",
  offline: "Keep cached story or task visible and queue changes until connection returns.",
  apiDelay: "Show calm waiting feedback, keep the prior safe content visible, and prevent repeated taps.",
  apiFailure: "Explain the service problem in parent-readable language and offer retry or cached fallback.",
  disabled: "Explain the disabled reason near the control.",
  permissionDenied: "Send parent to consent or settings; never ask the child to solve it."
};

export const pages = [
  {
    id: "FL-HTML-01",
    title: "First Launch",
    route: "#/first-launch",
    renderer: "firstLaunch",
    audience: "Parent",
    ageBand: "Adult caregiver",
    businessGoal: "Convert first open into trusted child setup.",
    userGoal: "Understand the product and begin setup within one tap.",
    pain: "The parent needs proof this is child-safe before giving any data.",
    sitemap: "Entry / onboarding",
    navigation: "No bottom navigation; setup and login exits only.",
    journey: "Download -> first open -> trust check -> setup",
    userFlow: "Open app, read one promise, inspect safety proof, start setup.",
    taskFlow: "Review value, confirm parent-managed model, tap Set up my child.",
    layoutFamily: "Immersive first-run trust strip",
    components: ["brand mark", "story world preview", "trust strip", "primary CTA", "login link"],
    primaryCTA: "Set up my child",
    secondaryCTA: "I already have an account",
    copy: "Stories, growth, and bedtime for ages 0-6. Parent managed. No child account.",
    illustration: "Bright parent-and-child reading scene with gentle blocks and moon lamp.",
    interaction: "CTA advances to parent login; login link opens returning parent flow.",
    animation: "Hero art fades in once; reduced motion uses no transform.",
    accessibility: "Single H1, CTA first after explanation, contrast above AA, touch target 56px.",
    childSafety: "No direct child data entry; adult consent before child profile.",
    responsive: "320-412px single column; tablet centers the phone-width journey card.",
    api: "not applicable: no network before consent",
    states: commonStates,
    acceptance: ["Parent sees value within 3 seconds.", "No child account is requested.", "Only two forward choices are visible."],
    testIds: ["T-FIRST-001", "T-A11Y-001", "T-SAFE-001"]
  },
  {
    id: "FL-HTML-02",
    title: "Parent Login",
    route: "#/login",
    renderer: "login",
    audience: "Parent",
    ageBand: "Adult caregiver",
    businessGoal: "Create a consented parent session.",
    userGoal: "Log in without exposing adult credentials to the child.",
    pain: "Parents need a fast but secure gate before managing child data.",
    sitemap: "Entry / authentication",
    navigation: "Back to first launch; continue to child profile.",
    journey: "First open -> login -> child setup",
    userFlow: "Choose email or passkey, read privacy note, submit credentials.",
    taskFlow: "Enter email, enter password, log in, recover from validation errors.",
    layoutFamily: "Secure form with consent panel",
    components: ["email field", "password field", "privacy summary", "login CTA", "help link"],
    primaryCTA: "Log in",
    secondaryCTA: "Create parent account",
    copy: "Parent account required for consent, privacy choices, and progress review.",
    illustration: "Small lock and family notebook beside the form.",
    interaction: "Inline validation; submit locks button and shows loading state.",
    animation: "Field errors slide down 120ms; reduced motion shows instant message.",
    accessibility: "Labels are explicit; errors use aria-live; tab order follows form order.",
    childSafety: "Adult-only authentication; no child-facing encouragement to enter data.",
    responsive: "Form fields remain full width; help content moves under form on narrow screens.",
    api: "POST /auth/session",
    states: commonStates,
    acceptance: ["Invalid email shows inline error.", "Password is never shown by default.", "Privacy note links to parent policy."],
    testIds: ["T-AUTH-001", "T-ERROR-001", "T-A11Y-002"]
  },
  {
    id: "FL-HTML-03",
    title: "Create Child",
    route: "#/child",
    renderer: "childProfile",
    audience: "Parent",
    ageBand: "Adult caregiver",
    businessGoal: "Collect minimal child profile data for safe personalization.",
    userGoal: "Create a child profile with only necessary information.",
    pain: "Parents dislike apps asking for excessive child data.",
    sitemap: "Onboarding / child profile",
    navigation: "Back to login; continue to age band.",
    journey: "Login -> create child -> age input",
    userFlow: "Enter display name, choose avatar, confirm data minimization.",
    taskFlow: "Type nickname, select visual avatar, save profile.",
    layoutFamily: "Profile builder with data minimization checklist",
    components: ["nickname field", "avatar picker", "data checklist", "save CTA"],
    primaryCTA: "Continue to age",
    secondaryCTA: "Skip avatar",
    copy: "Use a nickname. We do not need a full name, photo, or birthday.",
    illustration: "Friendly guide character with selectable color badges.",
    interaction: "Avatar selection updates preview and save state.",
    animation: "Selected avatar gently scales once; reduced motion uses outline only.",
    accessibility: "Avatar choices have text labels; nickname field has helper text.",
    childSafety: "No full name, photo, location, school, or contact request.",
    responsive: "Avatar grid becomes two columns at 320px.",
    api: "POST /children",
    states: commonStates,
    acceptance: ["Full legal name is not requested.", "Save stays disabled until nickname exists.", "Avatar has accessible name."],
    testIds: ["T-CHILD-001", "T-PRIVACY-001", "T-STATE-001"]
  },
  {
    id: "FL-HTML-04",
    title: "Age Band",
    route: "#/age",
    renderer: "ageBand",
    audience: "Parent",
    ageBand: "0-2, 3-4, 5-6 child bands",
    businessGoal: "Set the cognitive baseline for recommendations.",
    userGoal: "Choose the child's age band and understand why it matters.",
    pain: "Parents need confidence that content matches development stage.",
    sitemap: "Onboarding / age band",
    navigation: "Back to child profile; continue to recommendation.",
    journey: "Create child -> choose age -> recommendation",
    userFlow: "Compare age bands, read ability notes, select one band.",
    taskFlow: "Select 0-2, 3-4, or 5-6, review guidance, confirm.",
    layoutFamily: "Age-specific comparison panels",
    components: ["age cards", "ability notes", "parent tip", "confirm CTA"],
    primaryCTA: "Use this age band",
    secondaryCTA: "Ask me later",
    copy: "Age changes story length, visual cues, questions, and bedtime pacing.",
    illustration: "Three developmental cards: look, name, tell.",
    interaction: "Selecting a band updates recommendation explanation.",
    animation: "Panel content crossfades; reduced motion swaps instantly.",
    accessibility: "Cards are radio buttons; selected state has text and border.",
    childSafety: "Age bands prevent reading-heavy UI for non-readers.",
    responsive: "Cards stack vertically on phones and form columns on tablet.",
    api: "PATCH /children/:id/age-band",
    states: commonStates,
    acceptance: ["2-year-old path states visual-first guidance.", "Selection is screen-reader announced.", "No precise birthdate required."],
    testIds: ["T-AGE-001", "T-COG-001", "T-A11Y-003"]
  },
  {
    id: "FL-HTML-05",
    title: "AI Story Recommendation",
    route: "#/recommendation",
    renderer: "recommendation",
    audience: "Parent",
    ageBand: "Selected child age band",
    businessGoal: "Start the first story with explainable personalization.",
    userGoal: "Pick a recommended story and know why it fits.",
    pain: "Parents do not trust black-box AI recommendations for children.",
    sitemap: "Home / today's story",
    navigation: "Bottom nav appears; play or browse alternatives.",
    journey: "Age band -> recommendation -> story player",
    userFlow: "Review recommended story, inspect fit reasons, start play.",
    taskFlow: "Read story card, verify age fit, tap Play story.",
    layoutFamily: "Explainable recommendation card plus alternatives",
    components: ["story hero", "fit reasons", "skill chips", "alternative list", "play CTA"],
    primaryCTA: "Play story",
    secondaryCTA: "See other stories",
    copy: "Recommended because Mia chose age 3-4, calm animals, and bedtime-friendly pacing.",
    illustration: "Forest story cover with soft animal characters.",
    interaction: "Alternative cards preview fit reasons before selecting.",
    animation: "Story card expands into player route; reduced motion uses fade.",
    accessibility: "Recommendation reasons are text, not only color chips.",
    childSafety: "No scary imagery, conflict, ads, or manipulative countdowns.",
    responsive: "Recommendation remains first; alternatives scroll horizontally on H5.",
    api: "GET /recommendations?childId=:id",
    states: commonStates,
    acceptance: ["Recommendation explains age fit.", "Parent can reject recommendation.", "Story start is one primary CTA."],
    testIds: ["T-REC-001", "T-PM-001", "T-SAFE-002"]
  },
  {
    id: "FL-HTML-06",
    title: "Child Story Player",
    route: "#/player",
    renderer: "player",
    audience: "Child with parent nearby",
    ageBand: "0-6, adapted by selected band",
    businessGoal: "Deliver the core story experience safely.",
    userGoal: "Listen, look, pause, and follow the story without reading.",
    pain: "Young children cannot use text-heavy playback controls.",
    sitemap: "Story / playback",
    navigation: "Back requires parent confirmation; finish leads to reflection.",
    journey: "Recommendation -> playback -> story end",
    userFlow: "Listen to page, use large controls, reach story end.",
    taskFlow: "Tap play or pause, swipe page, adjust volume with parent gate.",
    layoutFamily: "Immersive child player with oversized controls",
    components: ["story art", "progress dots", "large play button", "sound toggle", "parent gate"],
    primaryCTA: "Play or pause",
    secondaryCTA: "Parent controls",
    copy: "Look at the sleepy fox. Tap the big button to hear the next line.",
    illustration: "Full-screen calm illustrated scene with one focal character.",
    interaction: "Large central control toggles playback; swipe moves one story beat.",
    animation: "Scene pans slowly; reduced motion uses still image.",
    accessibility: "Audio captions available to parent; controls have labels.",
    childSafety: "No external links, purchases, ads, chat, or adult settings in child UI.",
    responsive: "Controls stay inside thumb zone and above device safe area.",
    api: "GET /stories/:id/pages and POST /progress/events",
    states: commonStates,
    acceptance: ["Primary control is at least 72px.", "Parent controls are gated.", "Offline cached story can continue."],
    testIds: ["T-PLAYER-001", "T-OFFLINE-001", "T-CHILD-UI-001"]
  },
  {
    id: "FL-HTML-07",
    title: "Story Complete",
    route: "#/complete",
    renderer: "complete",
    audience: "Child and parent",
    ageBand: "0-6, visual-first",
    businessGoal: "Convert completion into learning reflection.",
    userGoal: "Celebrate gently and answer one simple prompt.",
    pain: "Overstimulating rewards can disrupt bedtime and attention.",
    sitemap: "Story / completion",
    navigation: "Ask together, next story, or bedtime path.",
    journey: "Playback -> story complete -> reflection",
    userFlow: "See completion, answer one question, choose next step.",
    taskFlow: "Review visual recap, tap one feeling answer, continue.",
    layoutFamily: "Calm completion with one reflection prompt",
    components: ["completion scene", "single prompt", "visual answer buttons", "next CTA"],
    primaryCTA: "Ask together",
    secondaryCTA: "Choose next story",
    copy: "The fox found the quiet light. How did the fox feel?",
    illustration: "Soft recap card showing the ending moment.",
    interaction: "Answer buttons give gentle audio and visual confirmation.",
    animation: "Small sparkle fade only; bedtime removes celebration motion.",
    accessibility: "Prompt can be read aloud; visual answers include labels.",
    childSafety: "No streak pressure, no variable reward loop, no social comparison.",
    responsive: "Answer buttons form a two-by-two visual grid on phones.",
    api: "POST /progress/reflection",
    states: commonStates,
    acceptance: ["Only one prompt is shown.", "Reward is calm.", "Parent can skip reflection."],
    testIds: ["T-COMPLETE-001", "T-REWARD-001", "T-BEDTIME-SAFE-001"]
  },
  {
    id: "FL-HTML-08",
    title: "Next Recommendation",
    route: "#/next",
    renderer: "nextChoice",
    audience: "Parent",
    ageBand: "Adult caregiver",
    businessGoal: "Guide the next session without endless scrolling.",
    userGoal: "Choose continue, save, or stop confidently.",
    pain: "Parents need boundaries after a child finishes content.",
    sitemap: "Story / next step",
    navigation: "Home, saved list, bedtime, or daily task.",
    journey: "Story complete -> next recommendation -> task or bedtime",
    userFlow: "Review next option, inspect time estimate, decide.",
    taskFlow: "Choose next story, save for later, or start bedtime mode.",
    layoutFamily: "Decision board with time and stimulation labels",
    components: ["next story card", "time badge", "calmness meter", "save action", "stop action"],
    primaryCTA: "Save for later",
    secondaryCTA: "Start now",
    copy: "Next best: The Little Rain Drum. 4 minutes. Calm pace.",
    illustration: "Mini cover paired with time and energy indicators.",
    interaction: "Selecting stop recommends bedtime or parent task.",
    animation: "Cards slide less than 16px; reduced motion disables movement.",
    accessibility: "Time and calmness are text; not color-only.",
    childSafety: "No infinite autoplay; next story requires parent decision.",
    responsive: "Decision cards stack; destructive stop is visually separated.",
    api: "GET /recommendations/next",
    states: commonStates,
    acceptance: ["No autoplay chain.", "Time estimate is visible.", "Stop option is equal clarity."],
    testIds: ["T-NEXT-001", "T-DARKPATTERN-001", "T-UX-001"]
  },
  {
    id: "FL-HTML-09",
    title: "Daily Parent Task",
    route: "#/daily-task",
    renderer: "dailyTask",
    audience: "Parent",
    ageBand: "Adult caregiver leading child",
    businessGoal: "Extend story into one realistic parent-child activity.",
    userGoal: "Complete a short daily task with the child.",
    pain: "Parents need easy follow-up activities, not homework.",
    sitemap: "Daily tasks",
    navigation: "Task tab with back to home and completion route.",
    journey: "Next recommendation -> daily task -> parent interaction",
    userFlow: "Read task, gather object, start with child, mark progress.",
    taskFlow: "Choose 3-minute task, follow steps, mark done or skip.",
    layoutFamily: "Checklist activity with object cue",
    components: ["task card", "object cue", "three steps", "timer", "mark done CTA"],
    primaryCTA: "Start with child",
    secondaryCTA: "Skip today",
    copy: "Find something soft. Ask: What sound would it make in the rain story?",
    illustration: "Soft object and rain drum activity visual.",
    interaction: "Timer starts only after parent taps start; skip asks for reason.",
    animation: "Timer ring progresses smoothly; reduced motion uses numeric timer.",
    accessibility: "Steps are ordered text; timer does not rely on animation.",
    childSafety: "Activity uses safe household object and adult supervision.",
    responsive: "Checklist remains readable with 48px rows at 320px.",
    api: "GET /daily-tasks and POST /tasks/:id/start",
    states: commonStates,
    acceptance: ["Task takes under 5 minutes.", "Adult supervision is explicit.", "Skip path exists."],
    testIds: ["T-TASK-001", "T-SUPERVISION-001", "T-STATE-002"]
  },
  {
    id: "FL-HTML-10",
    title: "Parent Child Interaction",
    route: "#/interaction",
    renderer: "interaction",
    audience: "Parent and child together",
    ageBand: "3-6 with parent adaptation",
    businessGoal: "Increase parent-child engagement quality.",
    userGoal: "Guide a simple conversation without scripting the child.",
    pain: "Parents want prompts that feel natural, not robotic.",
    sitemap: "Daily tasks / interaction",
    navigation: "From daily task; exit to progress dashboard.",
    journey: "Daily task -> interaction -> progress",
    userFlow: "Read parent prompt, child responds visually or verbally, parent marks outcome.",
    taskFlow: "Ask, observe, choose response type, save note.",
    layoutFamily: "Split-role interaction board",
    components: ["parent prompt", "child visual choices", "observation note", "mark done CTA"],
    primaryCTA: "Mark done",
    secondaryCTA: "Save note only",
    copy: "Parent asks: Which sound was soft? Child can point, say, or tap.",
    illustration: "Two-panel parent-child prompt with pointing choices.",
    interaction: "Parent notes response; child choices are large and optional.",
    animation: "Choice confirmation pulses once; reduced motion uses check mark.",
    accessibility: "Parent instructions and child choices are separated semantically.",
    childSafety: "Does not grade the child; accepts pointing, sound, or silence.",
    responsive: "Parent panel appears before child choices on small screens.",
    api: "POST /interactions",
    states: commonStates,
    acceptance: ["No wrong-answer language.", "Multiple response modes are accepted.", "Parent note can be saved privately."],
    testIds: ["T-INTERACT-001", "T-INCLUSION-001", "T-NOTE-001"]
  },
  {
    id: "FL-HTML-11",
    title: "Parent Dashboard",
    route: "#/dashboard",
    renderer: "dashboard",
    audience: "Parent",
    ageBand: "Adult caregiver",
    businessGoal: "Show growth signals and next best parent action.",
    userGoal: "Review progress without over-measuring the child.",
    pain: "Parents need insight but not pressure or comparison.",
    sitemap: "Parent center / progress",
    navigation: "Parent tab; links to privacy, export, settings, bedtime.",
    journey: "Interaction -> progress review -> bedtime",
    userFlow: "Review week, read pattern, choose next action.",
    taskFlow: "Open dashboard, inspect signal cards, start bedtime or privacy action.",
    layoutFamily: "Parent analytics with humane progress language",
    components: ["weekly summary", "skill signals", "privacy shortcuts", "bedtime CTA"],
    primaryCTA: "Review progress",
    secondaryCTA: "Start bedtime",
    copy: "Mia listened calmly 4 times and answered with pointing twice this week.",
    illustration: "Gentle progress cards, no leaderboard.",
    interaction: "Cards expand for evidence; privacy actions require parent session.",
    animation: "Charts fill once; reduced motion shows completed bars.",
    accessibility: "Charts include text summaries and table fallback.",
    childSafety: "No comparison, ranking, public sharing, or pressure metrics.",
    responsive: "Cards become one-column and retain data labels.",
    api: "GET /progress/summary",
    states: commonStates,
    acceptance: ["Progress is descriptive, not competitive.", "Privacy shortcut is visible.", "Chart has text equivalent."],
    testIds: ["T-DASH-001", "T-PRIVACY-002", "T-A11Y-004"]
  },
  {
    id: "FL-HTML-12",
    title: "Bedtime Mode",
    route: "#/bedtime",
    renderer: "bedtime",
    audience: "Parent and child",
    ageBand: "0-6 bedtime context",
    businessGoal: "Support repeat usage in a calm nightly routine.",
    userGoal: "Start a low-stimulation story and end cleanly.",
    pain: "Parents need the app to help bedtime, not extend screen time.",
    sitemap: "Bedtime",
    navigation: "From dashboard or next recommendation; exits to lock screen.",
    journey: "Progress review -> bedtime -> end session",
    userFlow: "Dim interface, choose calm story, play, end with no autoplay.",
    taskFlow: "Set duration, start bedtime story, finish and lock next actions.",
    layoutFamily: "Low-stimulation night routine",
    components: ["dim theme", "duration picker", "calm story card", "night controls", "end session CTA"],
    primaryCTA: "Start bedtime story",
    secondaryCTA: "End tonight",
    copy: "One calm story. No autoplay. Screen dims after the final page.",
    illustration: "Moonlit room, soft blanket, single calm focal image.",
    interaction: "Duration picker changes story length; end disables next-story prompts.",
    animation: "No bounce; only slow opacity. Reduced motion uses static dimming.",
    accessibility: "High contrast in dark mode; audio can continue with screen dimmed.",
    childSafety: "No autoplay, no streak, no bright reward, no endless scroll.",
    responsive: "Controls stay low in thumb zone; dark mode respects safe areas.",
    api: "POST /bedtime/session",
    states: commonStates,
    acceptance: ["No next-story autoplay.", "End state is obvious.", "Brightness and motion are reduced."],
    testIds: ["T-BEDTIME-001", "T-MOTION-001", "T-AUTOPLAY-001"]
  }
];

const architecturePages = [
  ["FL-HTML-13", "Splash", "#/splash", "splashSystem", "Parent and child nearby", "0-6 family entry", "Confirm app identity and load cached session safely.", "Recognize FutureLight and continue without confusion.", "First launch can feel untrusted if branding and loading are unclear.", "Entry / launch", "Auto advances only after session check; parent can open help.", "App open -> identity -> session check -> next route", "Launch, verify brand, wait for session result.", "Open app, read brand, wait for route decision.", "Launch identity with session status rail", ["brand identity", "session status", "safe loading", "help action"], "Continue", "Help", "FutureLight opens with a calm identity screen and checks whether a parent session exists.", "Soft light mark with reading guide and child-safe loading rail.", "Auto route waits for session result; help opens parent support.", "Brand mark breathes once; reduced motion uses static mark.", "Brand text has readable contrast; loading status is announced.", "No child input, no tracking prompt, no external link.", "Keeps a centered mark at 320 and expands status rail on tablet.", "GET /session/status", "No session routes to onboarding; valid session routes to child home.", "T-SPLASH-001"],
  ["FL-HTML-14", "Onboarding", "#/onboarding", "onboardingSystem", "Parent", "Adult caregiver", "Explain the product model before account creation.", "Understand story, growth, privacy, and bedtime value.", "Parents reject vague AI products that do not explain control.", "Entry / onboarding", "Back to splash; next to consent.", "Splash -> onboarding -> consent", "Read three concrete product promises, continue to consent.", "Swipe or tap through concise cards, then continue.", "Three-panel product promise carousel", ["promise cards", "progress dots", "parent control note", "continue CTA"], "Review consent", "Back", "Stories are recommended by age, parent controls privacy, bedtime ends without autoplay.", "Three cards: story, growth, bedtime with concrete child-safe visuals.", "Dots and next button move one card; final CTA goes to consent.", "Cards slide 120ms; reduced motion swaps instantly.", "Cards use headings and are reachable by keyboard.", "No AI claim without parent control explanation.", "One card per view on phones; three columns on tablet.", "not applicable: local onboarding content", "Final card unlocks consent route.", "T-ONBOARD-001"],
  ["FL-HTML-15", "Parent Register", "#/register", "registerSystem", "Parent", "Adult caregiver", "Create a parent account for consent and data rights.", "Register with minimal required information.", "Parents need account setup without unnecessary child data.", "Entry / authentication", "Back to login; next to consent or create child.", "Onboarding -> register -> consent", "Enter parent email, create passphrase, accept account terms.", "Fill parent fields, submit, recover from validation errors.", "Parent registration form with privacy promise", ["email field", "passphrase field", "privacy promise", "submit CTA"], "Create parent account", "Use existing account", "Parent email is used for consent, deletion, export, and support.", "Secure parent notebook illustration.", "Validation appears inline; success routes to consent.", "Error messages reveal below fields; reduced motion is instant.", "Labels, errors, and password rules are explicit.", "Adult-only form; no child name or age requested here.", "Full-width form on phones; support panel on tablet.", "POST /parents", "Email already used shows recovery path.", "T-REGISTER-001"],
  ["FL-HTML-16", "Consent", "#/consent", "consentSystem", "Parent", "Adult caregiver", "Collect informed parental consent before personalization.", "Understand and approve child data use.", "Consent can be skipped or hidden in low-quality child apps.", "Entry / consent", "Back to onboarding/register; next to create child.", "Register -> consent -> create child", "Review child data summary, toggle permissions, accept.", "Read data use, open details, accept or decline.", "Consent ledger with explicit toggles", ["data summary", "permission toggles", "policy links", "accept CTA"], "Accept and continue", "Decline for now", "We use nickname, age band, story progress, and parent notes to personalize safely.", "Parent consent ledger with check marks and data categories.", "Toggles update summary; decline offers local-only explanation.", "Toggle feedback uses check mark; reduced motion no slide.", "Toggles have labels and state text.", "No personalization starts before adult consent.", "Toggles stack on mobile; details open as bottom sheet.", "POST /consent", "Decline routes to limited mode explanation.", "T-CONSENT-001"],
  ["FL-HTML-17", "Interest Selection", "#/interests", "interestSystem", "Parent with child input", "0-6 child preferences through parent", "Improve recommendations without asking unsafe personal questions.", "Choose safe story interests quickly.", "Parents need personalization that does not profile sensitive data.", "Onboarding / preferences", "Back to age; next to child home.", "Age -> interests -> child home", "Pick safe themes and avoid scary content.", "Select themes, set avoid list, continue.", "Visual interest board with safety avoid list", ["theme tiles", "avoid scary toggle", "age fit note", "continue CTA"], "Build Mia's home", "Skip interests", "Choose calm animals, music, bedtime, colors, or nature. Avoid scary stories by default.", "Tile grid with safe theme icons and parent avoid controls.", "Tiles toggle selected state; avoid list remains parent-controlled.", "Tile selection pops subtly; reduced motion uses border.", "Tiles have labels and selected text.", "No sensitive categories, no ads, no adult profiling.", "Two columns at 320; wider grid at tablet.", "PATCH /children/:id/interests", "Empty interests still allows age-based recommendations.", "T-INTEREST-001"],
  ["FL-HTML-18", "Child Home", "#/child-home", "childHomeSystem", "Child with parent nearby", "0-6 visual-first", "Anchor daily use around one clear next action.", "Know what to do next without reading-heavy UI.", "Children and parents get lost when home is a feature dump.", "Child area / home", "Bottom nav: Home, Stories, Task, Parent gate.", "Interests -> child home -> story or task", "See today's story, task, bedtime shortcut.", "Tap visual story card or parent-led task.", "Visual-first home with one primary story", ["today story", "large play CTA", "daily task", "parent gate"], "Play today's story", "Do today's task", "Mia's calm story is ready. Parent controls are behind the grown-up gate.", "Large story card with guide and calm animal cover.", "Card starts story; parent gate opens PIN.", "Card lift on press; reduced motion uses color.", "Large labels and aria names for controls.", "No settings, purchase, or external link in child area.", "Primary card remains above fold at 320.", "GET /home?childId=:id", "No content uses cached favorite and retry banner.", "T-HOME-001"],
  ["FL-HTML-19", "Story Explore", "#/stories", "exploreSystem", "Parent and child", "0-6 with parent guidance", "Let families browse safe story options without overwhelming choice.", "Find a story by age-safe theme.", "Too many categories create cognitive load.", "Story / explore", "Story tab; detail route; back to child home.", "Child home -> explore -> story detail", "Browse curated story shelves.", "Pick shelf, inspect story, open detail.", "Curated shelves with age-fit labels", ["shelf tabs", "story cards", "age labels", "filter chip"], "Open story", "Back home", "Explore calm, music, nature, and bedtime stories selected for Mia's age band.", "Shelf of child-safe covers with visible age-fit badges.", "Shelf chips filter cards; story card opens detail.", "Shelf changes fade; reduced motion swaps instantly.", "Filter chips expose selected state.", "No frightening themes, violence, ads, or infinite scroll pressure.", "Horizontal shelves on phone; grid on tablet.", "GET /stories", "Empty shelf offers different theme and retry.", "T-EXPLORE-001"],
  ["FL-HTML-20", "Category", "#/category", "categorySystem", "Parent and child", "0-6 category browsing", "Organize stories by safe developmental themes.", "Browse one category with clear boundaries.", "Generic categories do not explain age value.", "Story / category", "From explore; opens story detail.", "Explore -> category -> detail", "Select category and review suitable stories.", "Open category, scan age notes, choose story.", "Category lane with developmental rationale", ["category header", "age rationale", "story list", "back CTA"], "View story detail", "Change category", "Nature stories practice noticing, naming, and calm listening.", "Nature shelf with leaf trail and soft story covers.", "Story rows open detail; category change opens selector.", "Rows rise 6px on focus; reduced motion uses outline.", "Rows have text labels and age rationale.", "No unsafe or overstimulating stories appear in category results.", "Rows stack at 320; grid appears at 768.", "GET /stories?category=nature", "No stories shows parent-safe alternate category.", "T-CATEGORY-001"],
  ["FL-HTML-21", "Search", "#/search", "searchSystem", "Parent", "Adult caregiver", "Help parents find known content safely.", "Search by story, theme, or bedtime need.", "Search can expose unsafe or irrelevant results if uncontrolled.", "Story / search", "From explore; result opens detail.", "Child home -> search -> detail", "Enter query, inspect safe results, recover from no match.", "Type query, use safe suggestions, open detail.", "Parent search with guarded suggestions", ["search field", "safe suggestions", "result list", "empty recovery"], "Open result", "Clear search", "Search only returns child-safe stories and parent help content.", "Search card with suggestion chips and safe result rows.", "Typing updates suggestions; empty results show recovery.", "Result update is instant; reduced motion no shimmer.", "Search field has label and clear button.", "No open web search and no child-generated free text path.", "Input remains visible at small widths.", "GET /search?q=", "No result suggests category browse and retry.", "T-SEARCH-001"],
  ["FL-HTML-22", "Story Detail", "#/story-detail", "detailSystem", "Parent", "Adult caregiver", "Explain story fit before playback.", "Know length, age fit, skills, and safety before play.", "Parents need context before handing a player to a child.", "Story / detail", "From recommendation/explore/search; play route.", "Story selection -> detail -> player", "Review story summary and start or save.", "Inspect fit, preview skill, tap play.", "Story evidence sheet", ["cover", "summary", "age fit", "skill tags", "play CTA"], "Start story", "Save favorite", "A 4-minute calm story about rain sounds, naming soft/loud, and ending quietly.", "Story cover with fit and duration labels.", "Play starts child player; save updates favorites.", "Cover shared transition; reduced motion uses fade.", "Summary has text equivalent for cover.", "No scary elements; parent sees safety notes first.", "Cover top, evidence below on phone; split on tablet.", "GET /stories/:id", "Missing story opens recovery with safe alternatives.", "T-DETAIL-001"],
  ["FL-HTML-23", "Bedtime Player", "#/bedtime-player", "bedtimePlayerSystem", "Parent and child", "0-6 bedtime", "Deliver low-stimulation playback with hard stop.", "Listen to one bedtime story and end calmly.", "Autoplay and bright rewards disrupt sleep.", "Bedtime / playback", "From bedtime mode; ends to lock screen.", "Bedtime -> bedtime player -> end session", "Play calm story, dim, finish, stop.", "Start audio, follow dim page, end session.", "Dimmed audio-first player", ["dim art", "audio progress", "end session", "no autoplay notice"], "End session", "Pause", "The screen dims while the story continues. No next story starts automatically.", "Moonlit audio player with no bright reward.", "End session stops route; pause keeps dim mode.", "Slow opacity only; reduced motion static.", "Contrast is AA in dark mode and labels remain visible.", "No autoplay, no streak, no bright reward.", "Controls stay in lower safe area.", "POST /bedtime/session/events", "Audio error offers replay or end tonight.", "T-BEDPLAYER-001"],
  ["FL-HTML-24", "Favorites", "#/favorites", "favoritesSystem", "Parent", "Adult caregiver", "Let parents reuse trusted stories.", "Find saved stories without re-searching.", "Saved content must not become endless autoplay.", "Library / favorites", "From story detail or parent dashboard.", "Detail -> favorite -> favorites -> player/detail", "Save story, open favorites, choose one.", "Review saved list, open story, remove if needed.", "Saved story library with parent controls", ["saved list", "age labels", "remove action", "play detail CTA"], "Open saved story", "Remove saved story", "Saved stories keep age-fit labels and do not autoplay.", "Library shelf with small covers and parent actions.", "Remove asks confirmation; open goes to detail.", "Remove row fades; reduced motion instant.", "Remove buttons have clear labels.", "No public sharing or child social features.", "List rows are 56px minimum.", "GET /favorites", "Empty list suggests explore stories.", "T-FAVORITES-001"],
  ["FL-HTML-25", "History", "#/history", "historySystem", "Parent", "Adult caregiver", "Show past use without pressuring streaks.", "Review what was played and resume safely.", "Parents need history without gamified pressure.", "Library / history", "From parent center or favorites.", "Player -> history -> detail/replay", "Open history, inspect played story, choose replay.", "Scan recent sessions, open detail, clear entry.", "Calm history timeline", ["timeline", "session cards", "replay action", "privacy note"], "Replay story", "Clear entry", "History shows story title, date, and calm progress notes, without streaks.", "Soft timeline with story cards.", "Replay opens detail; clear entry requires parent confirmation.", "Timeline draw once; reduced motion static.", "Timeline has text order and dates.", "No comparison, ranking, or pressure metric.", "Timeline becomes simple list at 320.", "GET /history", "Empty history explains first story path.", "T-HISTORY-001"],
  ["FL-HTML-26", "Parent Entry", "#/parent-entry", "parentEntrySystem", "Parent gate", "Adult-only gate", "Protect adult controls from child access.", "Enter parent area intentionally.", "Child UI must not expose adult settings.", "Parent center / entry", "From bottom nav parent tab; next to PIN.", "Child home -> parent entry -> PIN", "Read grown-up gate and continue to PIN.", "Tap parent-only entry, confirm adult action.", "Grown-up gate with intent confirmation", ["adult notice", "reason list", "continue CTA", "child-safe exit"], "Continue to PIN", "Back to child home", "Grown-up area includes privacy, settings, progress, and screen time.", "Adult gate card separated from child UI.", "Continue opens PIN; back returns child home.", "Gate appears as bottom sheet; reduced motion static.", "Adult-only labels are explicit.", "Child cannot change settings without parent gate.", "Sheet is full width at 320.", "not applicable: local gate before PIN", "Back always returns to child-safe home.", "T-PARENTENTRY-001"],
  ["FL-HTML-27", "PIN Verification", "#/pin", "pinSystem", "Parent", "Adult caregiver", "Verify adult before sensitive controls.", "Unlock parent center quickly and safely.", "A weak gate lets children access settings.", "Parent center / PIN", "Back to parent entry; success to dashboard.", "Parent entry -> PIN -> dashboard", "Enter PIN, recover from invalid or timeout.", "Type PIN, submit, handle invalid code.", "PIN keypad with lockout feedback", ["PIN dots", "number pad", "forgot PIN", "unlock CTA"], "Unlock parent center", "Forgot PIN", "Enter your parent PIN. After 5 failed tries, use email recovery.", "Large keypad with secure dots.", "PIN digits fill dots; invalid code shows recovery.", "Dots update instantly; reduced motion no shake.", "Keypad buttons have accessible labels.", "Adult-only; lockout prevents child guessing.", "Keypad remains thumb reachable.", "POST /parent-gate/verify", "Invalid PIN shows retry and email recovery.", "T-PIN-001"],
  ["FL-HTML-28", "Screen Time", "#/screen-time", "screenTimeSystem", "Parent", "Adult caregiver", "Let parents set healthy session boundaries.", "Set daily duration and bedtime limits.", "Without boundaries, story apps can overextend usage.", "Parent center / screen time", "From dashboard; save returns dashboard.", "Dashboard -> screen time -> save", "Adjust session limit and bedtime stop.", "Set duration, set bedtime mode, save.", "Boundary settings panel", ["duration stepper", "bedtime stop", "save CTA", "explanation"], "Save limits", "Reset to recommended", "Recommended: one story or five minutes at bedtime, no autoplay.", "Limit sliders with calm explanation.", "Save persists settings; reset restores age recommendation.", "Slider feedback is immediate; reduced motion none.", "Inputs have labels and numeric text.", "No dark patterns; adult limits support child wellbeing.", "Stepper replaces slider at 320.", "PATCH /settings/screen-time", "Save failure keeps local changes and retry.", "T-SCREENTIME-001"],
  ["FL-HTML-29", "Growth Report", "#/growth-report", "growthSystem", "Parent", "Adult caregiver", "Translate usage into humane learning signals.", "Understand growth without comparing the child.", "Metrics can become pressure or false precision.", "Parent center / growth", "From dashboard; links to history and privacy.", "Dashboard -> growth report -> action", "Review signals, read evidence, choose next activity.", "Open report, expand signal, start activity.", "Humane growth signal report", ["signal cards", "evidence rows", "activity suggestion", "privacy note"], "Try suggested activity", "View history", "Mia often points to sound choices and prefers calm animal stories this week.", "Soft report cards with evidence rows.", "Signal expands evidence; CTA opens task.", "Cards expand 120ms; reduced motion instant.", "Charts have text summaries.", "No ranking, diagnosis, or social comparison.", "Report stacks at 320 and becomes columns at 768.", "GET /growth-report", "No data suggests first story path.", "T-GROWTH-001"],
  ["FL-HTML-30", "Privacy", "#/privacy", "privacySystem", "Parent", "Adult caregiver", "Provide child data rights and transparency.", "Export, delete, or review child data.", "Privacy controls hidden behind support create distrust.", "Parent center / privacy", "From dashboard/settings; actions require PIN.", "Dashboard -> privacy -> export/delete", "Review data map, export, delete, or contact support.", "Choose privacy action, confirm, recover from API error.", "Privacy action center", ["data map", "export CTA", "delete CTA", "support CTA"], "Export data", "Delete child profile", "Parent controls data export, deletion, and consent records.", "Data map with categories and parent actions.", "Delete opens confirmation; export starts request.", "Confirmation sheet fades; reduced motion instant.", "Actions are labelled and destructive action is separated.", "Parent-only; no child-facing deletion prompt.", "Destructive actions stay below explanatory text.", "POST /privacy/export and DELETE /children/:id", "API failure keeps request status and support path.", "T-PRIVACY-003"],
  ["FL-HTML-31", "Settings", "#/settings", "settingsSystem", "Parent", "Adult caregiver", "Centralize account, audio, language, and safety settings.", "Adjust product behavior without searching.", "Settings can become a confusing dump.", "Parent center / settings", "From dashboard; links to notification/privacy/screen time.", "Dashboard -> settings -> save", "Open settings, change one preference, save.", "Change audio, language, notifications, or privacy link.", "Grouped settings list", ["audio row", "language row", "notification row", "privacy link"], "Save settings", "Cancel", "Settings are grouped by child experience, parent account, and privacy.", "Quiet settings list with clear grouping.", "Rows open focused controls; save commits changes.", "Row press uses subtle color; reduced motion none.", "Rows are keyboard reachable and labelled.", "No child-accessible settings; parent gate is required.", "Rows stay 52px minimum at 320.", "PATCH /settings", "Save failure shows retry and preserves changes.", "T-SETTINGS-001"],
  ["FL-HTML-32", "Notification", "#/notification", "notificationSystem", "Parent", "Adult caregiver", "Let parents choose reminder timing and quiet hours.", "Control reminders without child pressure.", "Notifications can manipulate families if unclear.", "Parent center / notifications", "From settings; save returns settings.", "Settings -> notification -> save", "Choose reminders and quiet hours.", "Toggle reminders, set quiet hours, save.", "Reminder consent and quiet hours", ["reminder toggle", "quiet hours", "preview", "save CTA"], "Save reminder settings", "Turn off reminders", "Reminders are parent-facing only and stay silent during bedtime quiet hours.", "Calendar and moon reminder preview.", "Toggle updates preview; save persists.", "Preview fades; reduced motion instant.", "Toggles expose on/off text.", "No child-directed push pressure or streak reminders.", "Controls stack with clear labels.", "PATCH /notifications", "Permission denied explains OS settings.", "T-NOTIFY-001"],
  ["FL-HTML-33", "Offline", "#/offline", "offlineSystem", "Parent and child", "0-6 safe fallback", "Keep safe cached content available when network drops.", "Families need graceful offline behavior.", "Network drops can leave families unsure whether progress is lost.", "System / offline", "Appears over current route; retry or cached story.", "Any route -> offline -> recovery", "Show offline status, offer cached story or retry.", "Detect offline, keep prior content, retry.", "Offline recovery panel", ["offline banner", "cached story", "retry CTA", "status text"], "Use cached story", "Retry connection", "No internet. You can play the saved calm story or try again.", "Cloud-offline card with cached story option.", "Retry checks network; cached story opens player.", "Banner appears instantly; reduced motion static.", "Status is text, not color-only.", "No child blame or scary error language.", "Panel fits above bottom nav.", "GET /health/reconnect", "Retry failure keeps offline panel.", "T-OFFLINE-001"],
  ["FL-HTML-34", "Reconnect", "#/reconnect", "reconnectSystem", "Parent", "Adult caregiver", "Recover from dropped API calls predictably.", "Reconnect and resume without data loss.", "Dropped calls can lose parent choices.", "System / reconnect", "From offline/error; returns previous route.", "Offline -> reconnect -> previous route", "Check connection, sync queued events, return.", "Tap reconnect, watch sync, resume.", "Reconnect progress with queued changes", ["connection status", "queued events", "sync progress", "resume CTA"], "Resume", "Stay offline", "Connection restored. Two progress events will sync before returning.", "Sync rail with queued event chips.", "Resume disabled until sync completes.", "Progress bar fills; reduced motion numeric only.", "Progress has text percentage.", "No silent sync; queued child data is parent-readable.", "Progress rail stays within phone width.", "POST /sync", "Sync failure routes to offline with retry.", "T-RECONNECT-001"],
  ["FL-HTML-35", "Error Recovery", "#/error", "errorSystem", "Parent", "Adult caregiver", "Recover from app, content, token, or audio failures.", "Understand what failed and what to do next.", "Generic errors destroy trust.", "System / error", "From any failed route; retry, support, or safe home.", "Any route -> error -> retry/recovery", "Read issue, retry, use safe fallback, or contact support.", "Identify error type, choose recovery, return safe route.", "Structured error recovery center", ["error type", "recovery options", "support path", "safe home CTA"], "Retry now", "Go to child home", "Story audio could not load. Retry, use cached story, or return to child home.", "Calm error card with specific recovery options.", "Retry repeats request; safe home always works.", "No shaking or alarming motion.", "Error heading is explicit and aria-live.", "No frightening visuals or blame language.", "Recovery actions remain visible at 320.", "varies by failed route", "500, timeout, missing story, token invalid, and audio error all map to recovery choices.", "T-ERROR-001"]
];

pages.push(...architecturePages.map((item) => ({
  id: item[0],
  title: item[1],
  route: item[2],
  renderer: item[3],
  audience: item[4],
  ageBand: item[5],
  businessGoal: item[6],
  userGoal: item[7],
  pain: item[8],
  sitemap: item[9],
  navigation: item[10],
  journey: item[11],
  userFlow: item[12],
  taskFlow: item[13],
  layoutFamily: item[14],
  components: item[15],
  primaryCTA: item[16],
  secondaryCTA: item[17],
  copy: item[18],
  illustration: item[19],
  interaction: item[20],
  animation: item[21],
  accessibility: item[22],
  childSafety: item[23],
  responsive: item[24],
  api: item[25],
  recovery: item[26],
  states: commonStates,
  acceptance: [item[26], "Primary and secondary CTA are visible.", "Back and recovery path are defined."],
  testIds: [item[27], `${item[0]}-NAV`, `${item[0]}-RECOVERY`]
})));

export const sitemap = [
  "Entry: Splash, Onboarding, Register, Login, Consent",
  "Onboarding: Create Child, Age Selection, Interest Selection",
  "Child: Child Home, Recommendation, Explore, Category, Search, Detail, Player, Complete, Favorites, History",
  "Parent: Parent Entry, PIN, Dashboard, Screen Time, Growth Report, Privacy, Settings, Notification",
  "System: Offline, Reconnect, Error Recovery"
];

export const navigationMatrix = pages.map((page, index) => ({
  pageId: page.id,
  route: page.route,
  back: pages[Math.max(0, index - 1)].id,
  next: pages[Math.min(pages.length - 1, index + 1)].id,
  primaryCTA: page.primaryCTA,
  secondaryCTA: page.secondaryCTA,
  recovery: page.recovery || page.states.error
}));
